import pandas as pd

def save_journals_to_xlsx(journal_list, filename):
    """
    Saves a list of journal titles to an XLSX file.

    Args:
        journal_list: A list of strings, where each string is a journal title.
        filename: The name of the output XLSX file.
    """

    df = pd.DataFrame({'Journal Title': journal_list})
    df.to_excel(filename, index=False)

if __name__ == "__main__":
    journal_list = [
        "2D Materials",
        "Advances in Natural Sciences: Nanoscience and Nanotechnology",
        "Applied Physics Express",
        "The Astronomical Journal",
        "The Astrophysical Journal",
        "The Astrophysical Journal Letters",
        "The Astrophysical Journal Supplement Series",
        "Biofabrication",
        "Bioinspiration & Biomimetics",
        "Biomedical Materials",
        "Biomedical Physics & Engineering Express",
        "Chinese Physics B",
        "Chinese Physics C",
        "Chinese Physics Letters",
        "Classical and Quantum Gravity",
        "Communications in Theoretical Physics",
        "ECS Advances",
        "ECS Journal of Solid State Science and Technology",
        "ECS Meeting Abstracts",
        "ECS Sensors Plus",
        "The Electrochemical Society Interface",
        "Electronic Structure",
        "Engineering Research Express",
        "Environmental Research Communications",
        "Environmental Research Letters",
        "Environmental Research: Climate",
        "Environmental Research: Ecology",
        "Environmental Research: Energy",
        "Environmental Research: Food Systems",
        "Environmental Research: Health",
        "Environmental Research: Infrastructure and Sustainability",
        "Environmental Research: Water",
        "European Journal of Physics",
        "Europhysics Letters",
        "Flexible and Printed Electronics",
        "Fluid Dynamics Research",
        "Functional Composites and Structures",
        "IOP Conference Series: Earth and Environmental Science",
        "IOP Conference Series: Materials Science and Engineering",
        "International Journal of Extreme Manufacturing",
        "Inverse Problems",
        "Izvestiya: Mathematics",
        "Japanese Journal of Applied Physics",
        "Journal of Breath Research",
        "Journal of Cosmology and Astroparticle Physics",
        "Journal of Instrumentation",
        "Journal of Micromechanics and Microengineering",
        "Journal of Neural Engineering",
        "Journal of Optics",
        "Journal of Physics A: Mathematical and Theoretical",
        "Journal of Physics B: Atomic, Molecular and Optical Physics",
        "Journal of Physics Communications",
        "Journal of Physics D: Applied Physics",
        "Journal of Physics G: Nuclear and Particle Physics",
        "Journal of Physics: Complexity",
        "Journal of Physics: Condensed Matter",
        "Journal of Physics: Conference Series",
        "Journal of Physics: Energy",
        "Journal of Physics: Materials",
        "Journal of Physics: Photonics",
        "Journal of Radiological Protection",
        "Journal of Reliability Science and Engineering",
        "Journal of Semiconductors",
        "Journal of Statistical Mechanics: Theory and Experiment",
        "Journal of The Electrochemical Society",
        "Laser Physics",
        "Laser Physics Letters",
        "Machine Learning: Earth",
        "Machine Learning: Engineering",
        "Machine Learning: Health",
        "Machine Learning: Science and Technology",
        "Materials Futures",
        "Materials Research Express",
        "Materials for Quantum Technology",
        "Measurement Science and Technology",
        "Methods and Applications in Fluorescence",
        "Metrologia",
        "Modelling and Simulation in Materials Science and Engineering",
        "Nano Express",
        "Nano Futures",
        "Nanotechnology",
        "Neuromorphic Computing and Engineering",
        "New Journal of Physics",
        "Nonlinearity",
        "Nuclear Fusion",
        "Physica Scripta",
        "Physical Biology",
        "Physics Education",
        "Physics World",
        "Physics in Medicine & Biology",
        "Physics-Uspekhi",
        "Physiological Measurement",
        "The Planetary Science Journal",
        "Plasma Physics and Controlled Fusion",
        "Plasma Science and Technology",
        "Plasma Sources Science and Technology",
        "Progress in Biomedical Engineering",
        "Progress in Energy",
        "Publications of the Astronomical Society of the Pacific",
        "Quantum Electronics",
        "Quantum Science and Technology",
        "Reports on Progress in Physics",
        "Research Notes of the AAS",
        "Research in Astronomy and Astrophysics",
        "Russian Chemical Reviews",
        "Russian Mathematical Surveys",
        "Sbornik: Mathematics",
        "Semiconductor Science and Technology",
        "Smart Materials and Structures",
        "Superconductor Science and Technology",
        "Surface Topography: Metrology and Properties",
        "Sustainability Science and Technology"
    ]

    filename = r"/research_filter/database/iopscience_journal.xlsx"

    save_journals_to_xlsx(journal_list, filename)
    print(f"Journal list saved to {filename}")