"""Generate BibTeX entries for cited studies."""

from __future__ import annotations

import logging
import re
from pathlib import Path

log = logging.getLogger(__name__)


def _latex_escape(text: str) -> str:
    """Minimal LaTeX escaping for BibTeX field values."""
    replacements = [
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("^", r"\^{}"),
        ("~", r"\~{}"),
    ]
    for src, dst in replacements:
        text = text.replace(src, dst)
    return text


def _format_authors(author_str: str) -> str:
    """Convert 'Last, First; Last2, First2' → 'Last, First and Last2, First2'."""
    if not author_str:
        return "Unknown Author"
    # Split only on semicolons — never on the word "and" (breaks names like "Houshmand")
    parts = [a.strip() for a in author_str.split(";") if a.strip()]
    return " and ".join(parts)


def _clean_doi(doi: str) -> str:
    return doi.strip().lstrip("https://doi.org/").lstrip("http://dx.doi.org/")


def build_bibtex_entry(study: dict) -> str:
    key = study["citation_key"]
    title = _latex_escape(study.get("title", ""))
    author = _format_authors(study.get("author", ""))
    year = study.get("year", "0000")
    journal = _latex_escape(study.get("journal", ""))
    doi = _clean_doi(study.get("doi", ""))

    lines = [
        f"@article{{{key},",
        f'  author  = {{{_latex_escape(author)}}},',
        f'  title   = {{{{{title}}}}},',
        f'  year    = {{{year}}},',
    ]
    if journal:
        lines.append(f'  journal = {{{_latex_escape(journal)}}},')
    if doi:
        lines.append(f'  doi     = {{{doi}}},')
        lines.append(f'  url     = {{https://doi.org/{doi}}},')
    lines.append("}")
    return "\n".join(lines)


def build_bibtex_file(studies: list[dict], cited_keys: set[str] | None = None) -> str:
    """Build the full BibTeX content string.

    If *cited_keys* is provided, only include entries whose citation_key is in the set.
    """
    entries: list[str] = []
    seen: set[str] = set()

    for s in studies:
        key = s["citation_key"]
        if cited_keys is not None and key not in cited_keys:
            continue
        if key in seen:
            continue
        seen.add(key)
        entries.append(build_bibtex_entry(s))

    header = (
        "% BibTeX file generated by the fatigue-EEG literature-review pipeline.\n"
        "% Theme A — Limited Number of EEG Electrodes — Single-channel EEG\n\n"
    )
    return header + "\n\n".join(entries) + "\n"


def save_bibtex(content: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    log.info("BibTeX saved: %s (%d chars)", output_path, len(content))


def extract_cited_keys(tex_content: str) -> set[str]:
    """Return all citation keys used in a LaTeX string.

    Handles comma-separated keys inside a single \\cite{a,b,c}.
    """
    raw = re.findall(r"\\cite\{([^}]+)\}", tex_content)
    keys: set[str] = set()
    for group in raw:
        for k in group.split(","):
            k = k.strip()
            if k:
                keys.add(k)
    return keys
